apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-test-app-2
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: flask-test-app-2
    spec:
      containers:
      - name: flask-test-app-2
        image: bastianklein/flask-test-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: FLASK_APP
          value: 'testapp'
